### ISSUE TITLE
Review Security Control checklist and SOAR document

### ISSUE THREAD

**Issue by webgismd** [bcgov/nr-nerds#25]
**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

As a director, I want to know and tell the story about how DevOps can cover off items listed in the SOAR and Security control checklist.. two documents that can be used to get a signed STRA... this can also feed into the latest condos or SDLC standards.

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)
Given the completion of documentation. Then directors and newbs can understand the benefits of devops.

**Definition of Done**
- [x ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [x ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged
